export const vehicleMakes = [
  "Toyota",
  "Honda",
  "Nissan",
  "Mazda",
  "Subaru",
  "Mitsubishi",
  "Lexus",
  "Suzuki",
  "Daihatsu",
  "Isuzu",
  "Mercedes-Benz",
  "BMW",
  "Audi",
  "Volkswagen",
  "Porsche",
  "MINI",
  "Volvo",
  "Jaguar",
  "Land Rover",
  "Bentley",
  "Rolls-Royce",
  "Ferrari",
  "Lamborghini",
  "Maserati",
  "Alfa Romeo",
  "Fiat",
  "Aston Martin",
  "McLaren",
  "Peugeot",
  "Renault",
  "Citroen",
  "DS Automobiles",
  "Ford",
  "Chevrolet",
  "Cadillac",
  "Jeep",
  "Dodge",
  "Chrysler",
  "Lincoln",
  "GMC",
  "Tesla",
  "Hyundai",
  "Kia",
  "Genesis",
  "BYD",
  "NIO",
  "XPeng",
  "Li Auto",
  "Zeekr",
  "Lynk & Co",
  "Geely",
  "Polestar",
  "Lotus",
  "Smart",
  "Skoda",
  "Seat",
  "Cupra",
  "Opel",
  "Abarth",
  "Hummer",
  "Rivian",
  "Lucid",
] as const;

export const featuredBrands = vehicleMakes.slice(0, 30);

export const brandLogos: Partial<Record<(typeof vehicleMakes)[number], string>> = {
  Toyota: "/images/brands/toyota.svg",
  Honda: "/images/brands/honda.svg",
  Nissan: "/images/brands/nissan.svg",
  Mazda: "/images/brands/mazda.svg",
  Subaru: "/images/brands/subaru.svg",
  Mitsubishi: "/images/brands/mitsubishi.svg",
  Lexus: "/images/brands/lexus.svg",
  Suzuki: "/images/brands/suzuki.svg",
  Daihatsu: "/images/brands/daihatsu.svg",
  Isuzu: "/images/brands/isuzu.svg",
};
